### PR TITLE
Circumvent "Unknown CA" error during authorisation

### PR DESCRIPTION
**Pull request by SuibianP**
## Short Excerpt
Authorization fails with `Unknown CA` error. Added `hackney: [:insecure]` parameter into HTTPoison call in order to circumvent.

## Long Story
For some strange reason, the authorisation is unable to go through with the following error:
```
04:36:05.294 [info]  TLS :client: In state :certify at ssl_handshake.erl:1950 generated CLIENT ALERT: Fatal - Unknown CA

{:error,
 %HTTPoison.Error{
   id: nil,
   reason: {:tls_alert,
    {:unknown_ca,
     'TLS client: In state certify at ssl_handshake.erl:1950 generated CLIENT ALERT: Fatal - Unknown CA\n'}}
 }}
```
The error is not likely to be caused by incorrect credential due to the fact that:
- Purposedly inputting an wrong password produces `{:error, :invalid_credentials}` rather than the TLS handshake error.
- Use curl to send the very same POST request with intercepted token from `authorization.ex:68` without `-k` option produces
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
- Adding the `-k` option allows curl to return the responded token without problem.

## Reproducing
With the environment of Ubuntu 18.04.5 LTS, Erlang 23.1.5, and Elixir 1.11.2, the mere operation of invoking `vafs_jwt` function should be enough to reproduce this behaviour.

---
*(Sorry if the PR is much too spammy or otherwise bizarre in any way…… I'm a freshman without very much of a technical background if any at all :-C)*

### CODE REVIEW

**Comment by indocomsoft** [comment]
Ignoring certificates is actually unsafe.

Instead we should be adding `cacerts` from the `:certifi` package like so (this is for `HTTPoison.get/3`, it can easily be adapted for `HTTPoison.request/5`):
```elixir
HTTPoison.get("https://luminus.nus.edu.sg/", [], [ssl: [cacerts: :certifi.cacerts()]])
```

We should also add `certifi` to our list of dependencies in mix.exs.

Would you like to take this up? I can also fix this myself, but you're welcome to try to implement the fix I described :)

**Comment by SuibianP** [comment]
> Ignoring certificates is actually unsafe.
> 
> Instead we should be adding `cacerts` from the `:certifi` package like so (this is for `HTTPoison.get/3`, but it can easily be adapted for `HTTPoison.request/5`):
> 
> ```elixir
> HTTPoison.get("https://luminus.nus.edu.sg/", [], ssl: [cacerts: :certifi.cacerts()])
> ```
> 
> We should also add `certifi` to our list of dependencies in mix.exs.
> 
> Would you like to take this up? I can also fix this myself, but you're welcome to try to implement the fix I described :)

Sorry for my crude circumvention m(__)m
I am definitely willing to take it up and try to implement it. Please allow me some time if possible 🙇
Again, thank you very much for the patient detailed description!

**Comment by indocomsoft** [comment]
Yup, no worries. Thanks for reporting this too! Your bug report is very detailed and was very helpful to locate the reason for the error.

Just let me know if you need any help

**Comment by SuibianP** [comment]
I've attempted to achieve this in the new commit. It tested working and hopefully was not too far away from the right solution :rofl:

**Review by indocomsoft — APPROVED** [review]
LGTM

**Comment by indocomsoft** [comment]
Thanks for your contribution!

**Pull request merged**
